### ISSUE TITLE
生成dump文件

### ISSUE THREAD

**Issue by zhuhuanzi** [duyanming/Anno.Core#1]
大佬，您好
       我希望能在监控页面，可以方便的对某一个容器进行dump的查看与生成。虽然很多微服务开发引擎没提供这个，但是我认为这至关重要，因为这使得我在排查问题时十分容易。
        附，官方链接https://docs.microsoft.com/zh-cn/dotnet/core/diagnostics/dotnet-dump

**Comment by duyanming** [comment]
这个框架不仅仅是.netcore，还支持.netframework、java。后面还可能有其他语言，所以暂不考虑
